-- 0009_skill_summary.sql
--
-- 技能加 `summary` 列（施工文档 §24 的八要素补全）
--
-- ## 为什么需要
--
-- §24 要求 Skill 可"搜索 / 排序 / 组合 / 版本管理 / A/B 测试 /
-- 禁用 / 更新 / 删除"。这些能力都建立在**能快速判断某个技能是否适用**
-- 之上 —— 而技能名（`high_tension_emotion`）不足以判断。
--
-- Writer 检索到候选技能后要决定用哪几个，需要一个**一句话说明**
-- 它解决什么问题。没有这个字段，调用方只能把完整 rules/antiPatterns
-- 展开给模型判断，浪费上下文预算（§28 的预算是硬约束）。
--
-- ## 为什么单独一列而不是塞进 trigger_json
--
-- summary 是**展示**字段（给人/模型快速判断），
-- trigger 是**索引**字段（给代码做匹配）。
-- 两者用途不同、变更节奏不同，混在一起会让"改文案"变成"改索引"。

ALTER TABLE distilled_skills ADD COLUMN summary TEXT NOT NULL DEFAULT '';
